#!/bin/bash

#
# OpenDNS Stats Fetcher
# Brian Hartvigsen <brian.hartvigsen@opendns.com>
# Richard Crowley <richard@opendns.com>
#

RAWDATAURL="https://dashboard.opendns.com"
LOGINURL="https://login.opendns.com/?source=dashboard"

usage() {
	echo "Usage: $0 <username> <network_id> <YYYY-MM-DD> [<YYYY-MM-DD>] <output_file>" >&2
	exit 1
}

date_check() {
	case "$1" in
		[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9])
			;;
		*)
			echo "Error: dates must be in the YYYY-MM-DD form" >&2
			exit 2
			;;
	esac
}

USERNAME=$1
if [ -z "$USERNAME" ] ; then usage ; fi
NETWORK_ID="$2"
if [ -z "$NETWORK_ID" ] ; then usage ; fi
date_check "$3"
if [ -z "$4" ] ; then
	DATE="$3"
	OUTPUT_FILE="$5"
else
	date_check "$4"
	DATE="$3to$4"
	OUTPUT_FILE="$5"
fi

if [ -z "$OUTPUT_FILE" ] ; then usage ; fi

# Clear the output file at the start
> "$OUTPUT_FILE"
echo "Output will also be saved to $OUTPUT_FILE"

echo -n "Password for $USERNAME: " >&2
stty -echo
read PASSWORD
stty echo
echo "" >&2

PASSWORD=`echo -n "$PASSWORD" | od -A n -t x1 | tr -d '\n' | sed 's/ *$//;s/[ ]\{1,\}/%/g'`
USERNAME=`echo -n "$USERNAME" | od -A n -t x1 | tr -d '\n' | sed 's/ *$//;s/[ ]\{1,\}/%/g'`

COOKIEJAR=`mktemp /tmp/opendns-fetchstats-XXXXXX`

# Get the signin page's form token
FORMTOKEN=`curl --silent --insecure \
	--cookie-jar "$COOKIEJAR" \
	"$LOGINURL" \
	| grep -m 1 formtoken \
	| sed 's/^.*name="formtoken" value="\([0-9a-f]*\)".*$/\1/' \
`
echo "Form token: $FORMTOKEN"

# Sign into OpenDNS and follow the redirect
LOGIN_RESPONSE=$(curl --silent --insecure -L \
    --cookie "$COOKIEJAR" \
    --cookie-jar "$COOKIEJAR" \
    --data "formtoken=$FORMTOKEN&username=$USERNAME&password=$PASSWORD&sign_in_submit=foo" \
    "$LOGINURL"
)

# Check if we're successfully redirected to the dashboard
if echo "$LOGIN_RESPONSE" | grep -q "dashboard"; then
    echo "Login successful!"
else
    echo "Login failed. Check username and password." >&2
    exit 2
fi

# Fetch pages of Top Domains
GO="yes"
PAGE=1
while [ "yes" == "$GO" ] ; do
	echo "Fetching page $PAGE..."

	RAW=`curl --silent --insecure \
		--cookie "$COOKIEJAR" \
		"$RAWDATAURL/stats/$NETWORK_ID/topdomains/$DATE/page$PAGE.csv" \
	`
	
	if [ "$PAGE" == "1" ]; then
		if [ "$RAW" == "" ]; then
			echo "You can not access $NETWORK_ID" >&2
			exit 2
		fi
		HEADING=`echo "$RAW" | head -n 1`
		if [[ "$HEADING" == *DOCTYPE* ]]; then
		    echo "Error retrieving data. Date range may be outside of available data." >&2
	        exit 2
		fi
	else
		RAW=`echo "$RAW" | tail -n +2`
	fi

	if [ -z "$RAW" ] ; then 
		echo "No more data at page $PAGE."
		GO="no"
	else 
		echo "$RAW" >> "$OUTPUT_FILE"
	fi

	PAGE=$(($PAGE + 1))
done

echo "Finished fetching all pages."
rm -f "$COOKIEJAR"
